name: Docker ARM V7 Build

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.armv7
          platforms: linux/arm/v7
          push: true
          tags: libreddit/libreddit:armv7
          cache-from: type=gha
          cache-to: type=gha,mode=max
