name: Rust

on:
  push:
    branches:
      - 'main'
      - 'master'

  pull_request:
    branches:
      - 'main'
      - 'master'
    
jobs:
  check:
    name: cargo fmt --all -- --check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install minimal stable with rustfmt component
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check